#sudo & dist required so we can have py 3.7
sudo: required
dist: xenial

language: python

env:
- CFLAGS="-O0"

python:
- 3.5
- 3.6
- 3.7

install:
- pip install --upgrade pip
- pip install .

script:
- python tests.py

